//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptInvestment
    {
        public long AcceptIVID { get; set; }
        public Nullable<long> IdeaID { get; set; }
        public Nullable<long> MemberID { get; set; }
        public Nullable<long> QueryID { get; set; }
        public Nullable<decimal> AmountAccepted { get; set; }
        public Nullable<System.DateTime> CloseBeforeDate { get; set; }
    }
}
