//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public long AdminID { get; set; }
        public string AdminMobile { get; set; }
        public string AdminAddress { get; set; }
        public string AdminEmail { get; set; }
    }
}
