//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestorTC
    {
        public long InvestorTCID { get; set; }
        public Nullable<long> InvestorID { get; set; }
        public string ShortProfileDesc { get; set; }
        public string EducationDetails { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
