//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investor
    {
        public long InvestorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string InvestorAddress { get; set; }
        public string InvestorMobile { get; set; }
        public string InvestorEmail { get; set; }
    }
}
