//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sample1212Entities : DbContext
    {
        public Sample1212Entities()
            : base("name=Sample1212Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcceptInvestment> AcceptInvestments { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<IdeaDocument> IdeaDocuments { get; set; }
        public virtual DbSet<IdeaRisk> IdeaRisks { get; set; }
        public virtual DbSet<InvestmentPayment> InvestmentPayments { get; set; }
        public virtual DbSet<Investor> Investors { get; set; }
        public virtual DbSet<InvestorDocument> InvestorDocuments { get; set; }
        public virtual DbSet<InvestorTC> InvestorTCs { get; set; }
        public virtual DbSet<IVRequest> IVRequests { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<UserTC> UserTCs { get; set; }
        public virtual DbSet<WorkClosure> WorkClosures { get; set; }
        public virtual DbSet<WorkProgress> WorkProgresses { get; set; }
    }
}
