//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public long QueryID { get; set; }
        public string QueryDescription { get; set; }
        public Nullable<System.DateTime> QueryDate { get; set; }
    }
}
