//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public long SolutionID { get; set; }
        public string SolutionDescription { get; set; }
        public Nullable<System.DateTime> SolutionDate { get; set; }
        public Nullable<decimal> TentativeBudget { get; set; }
    }
}
