//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public long SubCategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public Nullable<decimal> MaxInvLimit { get; set; }
        public Nullable<decimal> MinInvLimit { get; set; }
    }
}
