//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTesting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTC
    {
        public long UserTCID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string UserAddress { get; set; }
        public string UserEmail { get; set; }
        public string UserMobile { get; set; }
    }
}
